Admin\MailingListBundle\Entity\Subscriber:
    type: entity
    table: admin_mailing_list_subscriber
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        forename:
            type: string
        surname:
            type: string
        email:
            type: string
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update

