Perform\MailingListBundle\Entity\Subscriber:
    type: entity
    table: perform_mailing_list_subscriber_queue
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        email:
            type: string
        connectorName:
            type: string
        list:
            type: string
        attributes:
            type: json_array
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
