subscribers:
    resource: "PerformMailingListBundle:LocalSubscriber"
    type:     crud
    prefix: /subscribers

lists:
    resource: "PerformMailingListBundle:LocalList"
    type:     crud
    prefix: /lists
