subscribers:
    resource: "perform_mailing_list.local_subscriber"
    type:     crud
    prefix: /subscribers

lists:
    resource: "perform_mailing_list.local_list"
    type:     crud
    prefix: /lists
