services:
    perform_mailing_list.crud.local_subscriber:
        class: Perform\MailingListBundle\Crud\LocalSubscriberCrud
        tags:
            - {name: perform_base.admin, entity: "PerformMailingListBundle:LocalSubscriber"}

    perform_mailing_list.crud.local_list:
        class: Perform\MailingListBundle\Crud\LocalListCrud
        tags:
            - {name: perform_base.admin, entity: "PerformMailingListBundle:LocalList"}

    perform_mailing_list.menu.mailing_list:
        class: Perform\MailingListBundle\Menu\MailingListLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: mailing_list }

    perform_mailing_list.form_factory:
        class: Perform\MailingListBundle\Form\UniqueFormFactory
        arguments:
            - "@form.factory"

    perform_mailing_list.twig.form:
        class: Perform\MailingListBundle\Twig\Extension\FormExtension
        arguments:
            - "@perform_mailing_list.form_factory"
        tags:
            - {name: twig.extension}

    perform_mailing_list.panel.subscribers:
        class: Perform\MailingListBundle\Panel\SubscribersPanel
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@twig"

    perform_mailing_list.manager:
        class: Perform\MailingListBundle\SubscriberManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - []
            - []
            - "@logger"
        tags:
            - {name: monolog.logger, channel: mailing_list}

    perform_mailing_list.listener.flush_subscribers:
        public: false
        class: Perform\MailingListBundle\EventListener\FlushSubscribersListener
        arguments:
            - "@perform_mailing_list.manager"
            - "@logger"
        tags:
            - {name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate}
            - {name: monolog.logger, channel: mailing_list}

    perform_mailing_list.enricher.user:
        public: false
        class: Perform\MailingListBundle\Enricher\UserEnricher
        arguments:
            - "@perform_user.repo.user"
        tags:
            - perform_mailing_list.enricher

    perform_mailing_list.command.process:
        public: false
        class: Perform\MailingListBundle\Command\ProcessQueueCommand
        arguments:
            - "@perform_mailing_list.manager"
        tags:
            - {name: console.command, command: 'perform:mailing-list:process-queue'}
