services:
    perform_mailing_list.admin.local_subscriber:
        class: Perform\MailingListBundle\Admin\LocalSubscriberAdmin
        tags:
            - {name: perform_base.admin, entity: "PerformMailingListBundle:LocalSubscriber"}

    perform_mailing_list.admin.local_list:
        class: Perform\MailingListBundle\Admin\LocalListAdmin
        tags:
            - {name: perform_base.admin, entity: "PerformMailingListBundle:LocalList"}

    perform_mailing_list.menu.mailing_list:
        class: Perform\MailingListBundle\Menu\MailingListLinkProvider
        tags:
            - { name: perform_base.link_provider, alias: mailing_list }

    perform_mailing_list.form_factory:
        class: Perform\MailingListBundle\Form\UniqueFormFactory
        arguments:
            - "@form.factory"

    perform_mailing_list.twig.form:
        class: Perform\MailingListBundle\Twig\Extension\FormExtension
        arguments:
            - "@perform_mailing_list.form_factory"
        tags:
            - {name: twig.extension}

    perform_mailing_list.panel.subscribers:
        class: Perform\MailingListBundle\Panel\SubscribersPanel
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"

    perform_mailing_list.connector.local:
        class: Perform\MailingListBundle\Connector\LocalConnector
        arguments:
            - "@doctrine.orm.entity_manager"

    perform_mailing_list.manager:
        class: Perform\MailingListBundle\SubscriberManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@perform_mailing_list.connector.local"
        tags:
            - {name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate}
