services:
    admin_mailing_list.admin.subscriber:
        class: Perform\MailingListBundle\Admin\SubscriberAdmin
        tags:
            - {name: admin_base.admin, entity: "PerformMailingListBundle:Subscriber"}

    admin_mailing_list.form.handler.subscriber:
        class: Perform\MailingListBundle\Form\Handler\SubscriberFormHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@logger"

    admin_mailing_list.menu.mailing_list:
        class: Perform\MailingListBundle\Menu\MailingListLinkProvider
        tags:
            - { name: admin_base.link_provider, alias: mailing_list }

    admin_mailing_list.twig.form:
        class: Perform\MailingListBundle\Twig\Extension\FormExtension
        arguments:
            - "@form.factory"
        tags:
            - {name: twig.extension}

    admin_mailing_list.panel.subscribers:
        class: Perform\MailingListBundle\Panel\SubscribersPanel
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"
