services:
    admin_mailing_list.admin.subscriber:
        class: Admin\MailingListBundle\Admin\SubscriberAdmin
        tags:
            - {name: admin_base.admin, entity: "AdminMailingListBundle:Subscriber"}

    admin_mailing_list.form.handler.subscriber:
        class: Admin\MailingListBundle\Form\Handler\SubscriberFormHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@logger"

    admin_mailing_list.twig.form:
        class: Admin\MailingListBundle\Twig\Extension\FormExtension
        arguments:
            - "@form.factory"
        tags:
            - {name: twig.extension}

    admin_mailing_list.panel.subscribers:
        class: Admin\MailingListBundle\Panel\SubscribersPanel
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating"
